### ISSUE TITLE
Model thoughts

### ISSUE THREAD

**Issue by joeflack4** [timsbiomed/tccm-model-lite#2]
## Description
Possible things to change related to the model.

### `narrower_than` slot
This is probably just my limited understanding, but aren't "broader" and "narrower" opposites. I suppose it just depends on the position of the subject and predicate in `skos:broader`, but I wonder if this is possibly a mistake. Just want to verify.
```yml
  narrower_than:
    range: ConceptReference
    description: |-
      A reference to a SKOS concept whose intended meaning or extension is broader than this entry in the defining concept
      system
    slot_uri: skos:broader
    multivalued: true
    required: false
```

### `concept_uri` & `code_set_uri` alias
This could be a mist-understanding of mine as to how LinkML aliases work, but if it's an alias, do range and identifier have to actually be defined?
```yml
  concept_uri:
    range: uriorcurie
    description: |-
      The URI or CURIE of a code entry
    identifier: true
    alias: uri
```
```py
class ConceptReferenceUri(URIorCURIE):
    pass
```

```yml
code_set_uri:
    range: uriorcurie
    description: |-
      The URI or CURIE of a code set 
    identifier: true
    alias: uri
```
```py
class CodeSetUri(URIorCURIE):
    pass
```

```yml
  concept_system_uri:
    range: uriorcurie
    description: |-
      The URI or CURIE of a concept system 
    identifier: true
    alias: uri
```
```py
class ConceptSystemUri(URIorCURIE):
    pass
```
